platform :ios, '11.0'
workspace 'WebimMobileSDK'
use_frameworks!

install! 'cocoapods', :deterministic_uuids => false

target 'WebimMobileSDK_Example' do
    pod 'WebimMobileSDK'
    pod 'WebimMobileWidget', '1.2.1'
    pod 'WebimKeyboard', '1.0.2'

    pod 'SQLite.swift', :git => 'https://github.com/stephencelis/SQLite.swift.git', :tag => '0.15.0'    
    pod 'Firebase/Crashlytics'
    pod 'Firebase/Analytics'
    
    target 'WebimClientShare' do
        use_frameworks!
        pod 'WebimMobileSDK'
        project 'WebimMobileSDK.xcodeproj'
    end

    target 'WebimMobileSDK_Tests' do
        inherit! :search_paths
    end
    
    post_install do |installer|
      installer.pods_project.targets.each do |target|

       target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
          config.build_settings['SWIFT_VERSION'] = '5.0'
       end

        target.build_configurations.each do |config|
          if config.name == 'Debug'
            config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)', '-Onone']
            config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
          end
        end

        if target.name == 'SlackTextViewController' || target.name == 'WebimMobileWidget'
          target.build_configurations.each do |config|
            config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
          end
        end
      end
    end
    
end
