platform :ios, '11.0'
workspace 'WebimClientLibrary'
use_frameworks!

target 'WebimClientLibrary_Example' do
    target 'WebimClientShare' do
        use_frameworks!
        pod 'WebimMobileSDK', :path => '../'
        project 'WebimClientLibrary.xcodeproj'
    end   
    pod 'WebimMobileSDK', :path => '../'
    pod 'Firebase/Crashlytics'
    pod 'Firebase/Analytics'
    pod 'WebimMobileWidget', '1.0.1'

    target 'WebimClientLibrary_Tests' do
        inherit! :search_paths
    end
    
    post_install do |installer|
      installer.pods_project.targets.each do |target|
        if target.name == 'WebimMobileSDK' || target.name == 
'SQLite.swift' || target.name == 'Cosmos' || target.name == 'Nuke'
          target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '5.0'
          end
        else
          target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.2'
          end
        end

       target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
       end

        target.build_configurations.each do |config|
          if config.name == 'Debug'
            config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)', '-Onone']
            config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
          end
        end

        if target.name == 'SlackTextViewController' || target.name == 
'WebimMobileWidget'
          target.build_configurations.each do |config|
            config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
          end
        end
      end
    end
    
end
