//
//  VisitorItem.swift
//  WebimClientLibrary
//
//  Created by Nikita Lazarev-Zubov on 15.08.17.
//  Copyright © 2017 Webim. All rights reserved.
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.
//

import UIKit

/**
 Internal representation of visitor information.
 - author:
 Nikita Lazarev-Zubov
 - copyright:
 2017 Webim
 */
struct VisitorItem: Visitor {
    
    // MARK: - Constants
    // Raw values equal to field names received in responses from server.
    private enum JSONField: String {
        case icon = "icon"
        case id = "id"
        case fields = "fields"
    }
    
    // MARK: - Properties
    private var id: String
    private var icon: IconItem?
    private var visitorFields: VisitorFieldsItem?
    private var visitorFieldsDictionary: [String: String]?
    
    // MARK: - Initialization
    init?(jsonDictionary: [String: Any?]) {
        guard let id = jsonDictionary[JSONField.id.rawValue] as? String else {
            return nil
        }
        self.id = id
        
        if let visitorFieldsValue = jsonDictionary[JSONField.fields.rawValue] as? [String: String] {
            self.visitorFieldsDictionary = visitorFieldsValue
            self.visitorFields = VisitorFieldsItem(jsonDictionary: visitorFieldsValue)
        }
        
        if let iconValue = jsonDictionary[JSONField.icon.rawValue] as? [String : Any?] {
            icon = IconItem(jsonDictionary: iconValue)
        }
    }
    
    // MARK: - Methods
    
    func getIcon() -> Icon? {
        return icon
    }
    
    func getID() -> String {
        return id
    }
    
    func getVisitorFields() -> VisitorFields? {
        return visitorFields
    }
    
    func getVisitorFieldsInDictionary() -> [String: String]? {
        return visitorFieldsDictionary
    }
    
    
}

/**
 Representation of generated by server visitor avatar image of standard ones.
 - author:
 Nikita Lazarev-Zubov
 - copyright:
 2017 Webim
 */
struct IconItem: Icon {
    
    // MARK: - Constants
    private enum JSONField: String {
        case color = "color"
        case shape = "shape"
    }
    
    // MARK: - Properties
    private var color: UIColor?
    private var shape: String?
    
    // MARK: - Initialization
    init?(jsonDictionary: [String: Any?]) {
        if let color = jsonDictionary[JSONField.color.rawValue] as? UIColor {
            self.color = color
        }
        
        if let shape = jsonDictionary[JSONField.shape.rawValue] as? String {
            self.shape = shape
        }
    }
    
    // MARK: - Methods
    
    func getColor() -> UIColor? {
        return color
    }
    
    func getShape() -> String? {
        return shape
    }
    
}

// MARK: -
/**
 Internal representation of visitor fields.
 - author:
 Nikita Lazarev-Zubov
 - copyright:
 2017 Webim
 */
struct VisitorFieldsItem: VisitorFields {
    
    // MARK: - Constants
    // Raw values equal to field names received in responses from server.
    private enum JSONField: String {
        case name = "name"
        case phone = "phone"
        case email = "email"
        case firstCustomField = "first_custom_field"
        case secondCustomField = "second_custom_field"
        case thirdCustomField = "third_custom_field"
    }
    
    // MARK: - Properties
    private var name: String?
    private var email: String?
    private var phone: String?
    private var firstCustomField: String?
    private var secondCustomField: String?
    private var thirdCustomField: String?
    
    // MARK: - Initialization
    init?(jsonDictionary: [String : String?]) {
        if let name = jsonDictionary[JSONField.name.rawValue] {
            self.name = name
        }
        
        if let email = jsonDictionary[JSONField.email.rawValue] {
            self.email = email
        }
        
        if let phone = jsonDictionary[JSONField.phone.rawValue] {
            self.phone = phone
        }
        
        if let firstCustomField = jsonDictionary[JSONField.firstCustomField.rawValue] {
            self.firstCustomField = firstCustomField
        }
        
        if let secondCustomField = jsonDictionary[JSONField.secondCustomField.rawValue] {
            self.secondCustomField = secondCustomField
        }
        
        if let thirdCustomField = jsonDictionary[JSONField.thirdCustomField.rawValue] {
            self.thirdCustomField = thirdCustomField
        }
    }
    
    // MARK: - Methods
    
    func getName() -> String? {
        return name
    }
    
    func getEmail() -> String? {
        return email
    }
    
    func getPhone() -> String? {
        return phone
    }
    
    func getFirstCustomField() -> String? {
        return firstCustomField
    }
    
    func getSecondCustomField() -> String? {
        return secondCustomField
    }
    
    func getThirdCustomField() -> String? {
        return thirdCustomField
    }
}
